In [1]:
import pandas as pd
import numpy as np

In [2]:
file_path = "../Python/beginner datasets/wine.csv"
df = pd.read_csv(file_path)
df

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,type
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5,red
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,5,red
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,5,red
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6,red
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5,red
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6492,6.2,0.21,0.29,1.6,0.039,24.0,92.0,0.99114,3.27,0.50,11.2,6,white
6493,6.6,0.32,0.36,8.0,0.047,57.0,168.0,0.99490,3.15,0.46,9.6,5,white
6494,6.5,0.24,0.19,1.2,0.041,30.0,111.0,0.99254,2.99,0.46,9.4,6,white
6495,5.5,0.29,0.30,1.1,0.022,20.0,110.0,0.98869,3.34,0.38,12.8,7,white
6496,6.0,0.21,0.38,0.8,0.020,22.0,98.0,0.98941,3.26,0.32,11.8,6,white

In [31]:
# Qual Ã¨ la media di concentrazione alcolica per ogni qualitÃ ? Ci sono differenze? E rispetto alla media totale?
media_totale_perc_alc = df["alcohol"].mean().round(2)
print("\nla media totale della % alcool Ã¨ :", media_totale_perc_alc)
media_qualitÃ _perc_alc = df.groupby(["type", "quality"])["alcohol"].mean().round(2)
print("\nLa concentrazione media di alcool per qualitÃ  Ã¨:", media_qualitÃ _perc_alc)
differenza_rispetto_media_totale = media_qualitÃ _perc_alc - media_totale_perc_alc.round(2)
print("\nDifferenza rispetto alla media totale:", differenza_rispetto_media_totale)

la media totale della % alcool Ã¨ : 10.49

La concentrazione media di alcool per qualitÃ  Ã¨: type   quality
red    3           9.96
       4          10.27
       5           9.90
       6          10.63
       7          11.47
       8          12.09
white  3          10.34
       4          10.15
       5           9.81
       6          10.58
       7          11.37
       8          11.64
       9          12.18
Name: alcohol, dtype: float64

Differenza rispetto alla media totale: type   quality
red    3         -0.53
       4         -0.22
       5         -0.59
       6          0.14
       7          0.98
       8          1.60
white  3         -0.15
       4         -0.34
       5         -0.68
       6          0.09
       7          0.88
       8          1.15
       9          1.69
Name: alcohol, dtype: float64

In [25]:
# C'Ã¨ differenza nella concentrazione alcolica per vini bianchi e vini rossi?
conc_rosso = df.groupby("type")["alcohol"].mean().round(2)
print("\nLa concentrazione di alcool media per i vini Ã¨:", conc_rosso)

La concentrazione di alcool media per i vini Ã¨: type
red      10.42
white    10.51
Name: alcohol, dtype: float64

In [32]:
# Rifacendo le analisi delle domande precedenti ma per il pH, cambia qualcosa?
media_totale_ph= df["pH"].mean().round(2)
print("\nla media totale del ph :", media_totale_ph)
media_qualitÃ _ph = df.groupby(["type", "quality"])["pH"].mean().round(2)
print("\nil ph medio per qualitÃ  Ã¨:", media_qualitÃ _ph)
#differenza_rispetto_media_totale_ph = media_qualitÃ _ph - media_totale_ph.round(2)
#print("\nDifferenza rispetto alla media totale:", differenza_rispetto_media_totale_ph)

la media totale del ph : 3.22

il ph medio per qualitÃ  Ã¨: type   quality
red    3          3.40
       4          3.38
       5          3.30
       6          3.32
       7          3.29
       8          3.27
white  3          3.19
       4          3.18
       5          3.17
       6          3.19
       7          3.21
       8          3.22
       9          3.31
Name: pH, dtype: float64

In [34]:
# E per i solfati?
media_totale_solfati= df["sulphates"].mean().round(2)
print("\nla media totale del ph :", media_totale_solfati)
media_qualitÃ _solfati = df.groupby(["type","quality"])["sulphates"].mean().round(2)
print("\nil ph medio per qualitÃ  Ã¨:", media_qualitÃ _solfati)
differenza_rispetto_media_totale_ph = media_qualitÃ _solfati - media_totale_ph.round(2)
print("\nDifferenza rispetto alla media totale:", differenza_rispetto_media_totale_ph)

la media totale del ph : 0.53

il ph medio per qualitÃ  Ã¨: type   quality
red    3          0.57
       4          0.60
       5          0.62
       6          0.68
       7          0.74
       8          0.77
white  3          0.47
       4          0.48
       5          0.48
       6          0.49
       7          0.50
       8          0.49
       9          0.47
Name: sulphates, dtype: float64

Differenza rispetto alla media totale: type   quality
red    3         -2.65
       4         -2.62
       5         -2.60
       6         -2.54
       7         -2.48
       8         -2.45
white  3         -2.75
       4         -2.74
       5         -2.74
       6         -2.73
       7         -2.72
       8         -2.73
       9         -2.75
Name: sulphates, dtype: float64

In [22]:
media_elementi = df.groupby("quality")[["sulphates", "pH", "alcohol"]].mean() # le doppie quadre sono necessarie per indicare esplicitamente che stiamo passando piÃ¹ colonne al metodo groupby() sotto forma di una lista.
media_elementi

         sulphates        pH    alcohol
quality
3         0.506333  3.257667  10.215000
4         0.505648  3.231620  10.180093
5         0.526403  3.212189   9.837783
6         0.532549  3.217726  10.587553
7         0.547025  3.228072  11.386006
8         0.512487  3.223212  11.678756
9         0.466000  3.308000  12.180000